---
version: '2'
volumes:
  grafana:
  influxdb:

services:
  db:
    network_mode: bridge
    image: tutum/influxdb 
    ports:
      - "8083:8083"
      - "8086:8086"
    env_file:
      - ./env/db.env
    volumes:
     - "influxdb:/data"
  web:
    network_mode: bridge
    image: mtrnord/internet-speedtest-docker:grafana 
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      - GF_SERVER_ROOT_URL=http://speedtest.projectstreet.dynu.com
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - VIRTUAL_HOST=speedtest.projectstreet.dynu.com
    volumes:
     - "grafana:/var/lib/grafana"
  testing:
    network_mode: bridge
    image: mtrnord/internet-speedtest-docker:speedtest
    links:
      - db:db
    env_file:
      - ./env/testing.env
  nginx-proxy:
    network_mode: bridge
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy.conf:/etc/nginx/proxy.conf
  whoami:
    network_mode: bridge
    image: jwilder/whoami
    container_name: whoami
    environment:
      - VIRTUAL_HOST=whoami.local
