---
version: '2'
services:
  db:
    image: tutum/influxdb 
    ports:
      - "8083:8083"
      - "8086:8086"
    env_file:
      - ./env/db.env
  web:
    image: mtrnord/internet-speedtest-docker:grafana 
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      - VIRTUAL_HOST=speedtest.projectstreet.dynu.com
  testing:
    image: mtrnord/internet-speedtest-docker:speedtest
    links:
      - db:db
    env_file:
      - ./env/testing.env
  proxy:
    image: jwilder/nginx-proxy
    volume:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "80:80"
